import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./package.json");

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

console.log(`[ESBUILD] Building ${pkg.config.displayName} (${pkg.name}) v${pkg.version}`);

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["input.js"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    define: {
        "process.env.PLUGIN_NAME": JSON.stringify(pkg.config.displayName),
        "process.env.PLUGIN_ID": JSON.stringify(pkg.name),
        "process.env.PLUGIN_vp_ID": JSON.stringify(pkg.name), // Backwards compatibility if needed
    }
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
